'''
Accessible Access Control 1.0
2012-2104 Michigan Technological University
Supported in part by NSF grants: DUE-1140512, DUE-1245310 and IIS-1319363
Developer: Man Wang
Advisors:Dr. Steve Carr, Dr. Jean Mayo, Dr. Ching-Kuang Shene and Dr. Chaoli Wang
'''
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Desktop/test.ui'
#
# Created: Sat Nov  9 02:01:31 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    FONTSIZE = 12
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(499, 286)
        Dialog.setSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        font = QtGui.QFont()
        font.setPointSize(self.FONTSIZE) 
        Dialog.setFont(font)
        self.verticalLayoutWidget = QtGui.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 470, 261))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.groupBox.setGeometry(QtCore.QRect(self.groupBox.geometry().x(), self.groupBox.geometry().y(), 470 ,self.groupBox.geometry().height()))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        self.groupBox.setSizePolicy(sizePolicy)
        self.labQuestion1 = QtGui.QLabel(self.groupBox)
        self.labQuestion1.setGeometry(QtCore.QRect(10, 30, 470, 39))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.verticalLayout.addWidget(self.labQuestion1)
        
        font = QtGui.QFont()
        font.setPointSize(self.FONTSIZE)
        self.labQuestion1.setFont(font)
        self.labQuestion1.setWordWrap(True)
        self.labQuestion1.adjustSize()
        self.labQuestion1.setObjectName(_fromUtf8("labQuestion1"))
        self.widget = QtGui.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(10, 80, 470, 146))
        self.widget.setObjectName(_fromUtf8("widget"))

        self.radioButton_1 = QtGui.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(self.FONTSIZE)
        self.radioButton_1.setFont(font)
        self.radioButton_1.setObjectName(_fromUtf8("radioButton_1"))
        self.verticalLayout.addWidget(self.radioButton_1)
        self.radioButton_2 = QtGui.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(self.FONTSIZE)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtGui.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(self.FONTSIZE)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.verticalLayout.addWidget(self.radioButton_3)
        self.radioButton_4 = QtGui.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(self.FONTSIZE)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.verticalLayout.addWidget(self.radioButton_4)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.correctAnsLabel = QtGui.QLabel('')
        f = QtGui.QFont( "Arial", 15, QtGui.QFont.Bold)
        self.correctAnsLabel.setFont(f)
        self.verticalLayout_2.addWidget(self.correctAnsLabel)
        self.nextBtn = QtGui.QPushButton(self.verticalLayoutWidget)
        self.nextBtn.setObjectName(_fromUtf8("nextBtn"))
        self.verticalLayout_2.addWidget(self.nextBtn)
        
        self.labelChoice1 = QtGui.QLabel(self.groupBox)
        self.labelChoice1.setGeometry(QtCore.QRect(50, 90, 180, 180))
        self.labelChoice2 = QtGui.QLabel(self.groupBox)
        self.labelChoice2.setGeometry(QtCore.QRect(320, 90, 180, 180))
        self.labelChoice3 = QtGui.QLabel(self.groupBox)
        self.labelChoice3.setGeometry(QtCore.QRect(50, 270, 180, 180))
        self.labelChoice4 = QtGui.QLabel(self.groupBox)
        self.labelChoice4.setGeometry(QtCore.QRect(320, 270, 180, 180))
        self.labelChoice1.setVisible(False)
        self.labelChoice2.setVisible(False)
        self.labelChoice3.setVisible(False)
        self.labelChoice4.setVisible(False)
        Dialog.setLayout(self.verticalLayout_2)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Question 1", None, QtGui.QApplication.UnicodeUTF8))
        self.labQuestion1.setText(QtGui.QApplication.translate("Dialog", "According to the information on the interface, how many different categories exist in the whole system?", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_1.setText(QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_3.setText(QtGui.QApplication.translate("Dialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_4.setText(QtGui.QApplication.translate("Dialog", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.nextBtn.setText(QtGui.QApplication.translate("Dialog", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.labelChoice1.setText(QtGui.QApplication.translate("Dialog", "", None, QtGui.QApplication.UnicodeUTF8))
        self.labelChoice2.setText(QtGui.QApplication.translate("Dialog", "", None, QtGui.QApplication.UnicodeUTF8))
        self.labelChoice3.setText(QtGui.QApplication.translate("Dialog", "", None, QtGui.QApplication.UnicodeUTF8))
        self.labelChoice4.setText(QtGui.QApplication.translate("Dialog", "", None, QtGui.QApplication.UnicodeUTF8))
        self.correctAnsLabel.setText(QtGui.QApplication.translate("Dialog", "", None, QtGui.QApplication.UnicodeUTF8))

class Ui_ImageQuestion(object):
    IMAGESIZE = 200
    FONTSIZE = 10
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(700, 600)
        font = QtGui.QFont()
        font.setPointSize(self.FONTSIZE)
        Dialog.setFont(font)
        self.verticalLayoutWidget = QtGui.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 661, 581))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        #Dialog.setLayout(self.verticalLayout_2)
        self.groupBox = QtGui.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.labQuestion1 = QtGui.QLabel(self.groupBox)
        self.labQuestion1.setGeometry(QtCore.QRect(10, 30, 630, 39))
        font = QtGui.QFont()
        font.setPointSize(self.FONTSIZE)
        self.labQuestion1.setFont(font)
        self.labQuestion1.setText(_fromUtf8(""))
        self.labQuestion1.setWordWrap(True)
        self.labQuestion1.setObjectName(_fromUtf8("labQuestion1"))
        self.radioButton_1 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_1.setGeometry(QtCore.QRect(20, 180, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(self.FONTSIZE)
        self.radioButton_1.setFont(font)
        self.radioButton_1.setText(_fromUtf8(""))
        self.radioButton_1.setObjectName(_fromUtf8("radioButton_1"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(50, 100, 200, 200))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(360, 180, 21, 24))
        font = QtGui.QFont()
        font.setPointSize(self.FONTSIZE)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setText(_fromUtf8(""))
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.radioButton_3 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_3.setGeometry(QtCore.QRect(20, 400, 21, 24))
        font = QtGui.QFont()
        font.setPointSize(self.FONTSIZE)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setText(_fromUtf8(""))
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.radioButton_4 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_4.setGeometry(QtCore.QRect(360, 400, 21, 24))
        font = QtGui.QFont()
        font.setPointSize(self.FONTSIZE)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setText(_fromUtf8(""))
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(390, 100, 200, 200))
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(50, 320, 200, 200))
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(390, 320, 200, 200))
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_2.addWidget(self.groupBox)
        self.pushButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout_2.addWidget(self.pushButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Dialog", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        
class Ui_submission(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(520, 110)
        self.verticalLayoutWidget = QtGui.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 490, 70))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Submission", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Are you sure to submit and email the answers?", None, QtGui.QApplication.UnicodeUTF8))
        #self.label_1.setText(QtGui.QApplication.translate("Dialog", "Please enter the email address to send your answers to:", None, QtGui.QApplication.UnicodeUTF8))
        #self.label_2.setText(QtGui.QApplication.translate("Dialog", "Please input your name below:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Dialog", "Yes", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("Dialog", "No", None, QtGui.QApplication.UnicodeUTF8))