'''
Accessible Access Control 1.0
2012-2104 Michigan Technological University
Supported in part by NSF grants: DUE-1140512, DUE-1245310 and IIS-1319363
Developer: Man Wang
Advisors:Dr. Steve Carr, Dr. Jean Mayo, Dr. Ching-Kuang Shene and Dr. Chaoli Wang
Updated for PyQt6 compatibility
'''
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Desktop/test.ui'
# Updated for PyQt6 compatibility

from PyQt6 import QtCore, QtWidgets
from PyQt6.QtGui import QFont

class Ui_Dialog(object):
    FONTSIZE = 12
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(499, 286)
        Dialog.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        font = QFont()
        font.setPointSize(self.FONTSIZE) 
        Dialog.setFont(font)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 470, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.groupBox.setGeometry(QtCore.QRect(self.groupBox.geometry().x(), self.groupBox.geometry().y(), 470 ,self.groupBox.geometry().height()))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        self.groupBox.setSizePolicy(sizePolicy)
        self.labQuestion1 = QtWidgets.QLabel(self.groupBox)
        self.labQuestion1.setGeometry(QtCore.QRect(10, 30, 470, 39))
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.addWidget(self.labQuestion1)
        
        font = QFont()
        font.setPointSize(self.FONTSIZE)
        self.labQuestion1.setFont(font)
        self.labQuestion1.setWordWrap(True)
        self.labQuestion1.adjustSize()
        self.labQuestion1.setObjectName("labQuestion1")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(10, 80, 470, 146))
        self.widget.setObjectName("widget")

        self.radioButton_1 = QtWidgets.QRadioButton(self.widget)
        font = QFont()
        font.setPointSize(self.FONTSIZE)
        self.radioButton_1.setFont(font)
        self.radioButton_1.setObjectName("radioButton_1")
        self.verticalLayout.addWidget(self.radioButton_1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget)
        font = QFont()
        font.setPointSize(self.FONTSIZE)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.widget)
        font = QFont()
        font.setPointSize(self.FONTSIZE)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.widget)
        font = QFont()
        font.setPointSize(self.FONTSIZE)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout.addWidget(self.radioButton_4)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.correctAnsLabel = QtWidgets.QLabel('')
        f = QFont("Arial", 15, QFont.Weight.Bold)
        self.correctAnsLabel.setFont(f)
        self.verticalLayout_2.addWidget(self.correctAnsLabel)
        self.nextBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.nextBtn.setObjectName("nextBtn")
        self.verticalLayout_2.addWidget(self.nextBtn)
        
        self.labelChoice1 = QtWidgets.QLabel(self.groupBox)
        self.labelChoice1.setGeometry(QtCore.QRect(50, 90, 180, 180))
        self.labelChoice2 = QtWidgets.QLabel(self.groupBox)
        self.labelChoice2.setGeometry(QtCore.QRect(320, 90, 180, 180))
        self.labelChoice3 = QtWidgets.QLabel(self.groupBox)
        self.labelChoice3.setGeometry(QtCore.QRect(50, 270, 180, 180))
        self.labelChoice4 = QtWidgets.QLabel(self.groupBox)
        self.labelChoice4.setGeometry(QtCore.QRect(320, 270, 180, 180))
        self.labelChoice1.setVisible(False)
        self.labelChoice2.setVisible(False)
        self.labelChoice3.setVisible(False)
        self.labelChoice4.setVisible(False)
        Dialog.setLayout(self.verticalLayout_2)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Test"))
        self.groupBox.setTitle(_translate("Dialog", "Question 1"))
        self.labQuestion1.setText(_translate("Dialog", "According to the information on the interface, how many different categories exist in the whole system?"))
        self.radioButton_1.setText(_translate("Dialog", "3"))
        self.radioButton_2.setText(_translate("Dialog", "4"))
        self.radioButton_3.setText(_translate("Dialog", "8"))
        self.radioButton_4.setText(_translate("Dialog", "9"))
        self.nextBtn.setText(_translate("Dialog", "Next"))
        self.labelChoice1.setText(_translate("Dialog", ""))
        self.labelChoice2.setText(_translate("Dialog", ""))
        self.labelChoice3.setText(_translate("Dialog", ""))
        self.labelChoice4.setText(_translate("Dialog", ""))
        self.correctAnsLabel.setText(_translate("Dialog", ""))

class Ui_ImageQuestion(object):
    IMAGESIZE = 200
    FONTSIZE = 10
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 600)
        font = QFont()
        font.setPointSize(self.FONTSIZE)
        Dialog.setFont(font)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 661, 581))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        #Dialog.setLayout(self.verticalLayout_2)
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.labQuestion1 = QtWidgets.QLabel(self.groupBox)
        self.labQuestion1.setGeometry(QtCore.QRect(10, 30, 630, 39))
        font = QFont()
        font.setPointSize(self.FONTSIZE)
        self.labQuestion1.setFont(font)
        self.labQuestion1.setText("")
        self.labQuestion1.setWordWrap(True)
        self.labQuestion1.setObjectName("labQuestion1")
        self.radioButton_1 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_1.setGeometry(QtCore.QRect(20, 180, 20, 20))
        font = QFont()
        font.setPointSize(self.FONTSIZE)
        self.radioButton_1.setFont(font)
        self.radioButton_1.setText("")
        self.radioButton_1.setObjectName("radioButton_1")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(50, 100, 200, 200))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(360, 180, 21, 24))
        font = QFont()
        font.setPointSize(self.FONTSIZE)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setText("")
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setGeometry(QtCore.QRect(20, 400, 21, 24))
        font = QFont()
        font.setPointSize(self.FONTSIZE)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setText("")
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_4.setGeometry(QtCore.QRect(360, 400, 21, 24))
        font = QFont()
        font.setPointSize(self.FONTSIZE)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setText("")
        self.radioButton_4.setObjectName("radioButton_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(390, 100, 200, 200))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(50, 320, 200, 200))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(390, 320, 200, 200))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.groupBox)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Test"))
        self.pushButton.setText(_translate("Dialog", "PushButton"))
        
class Ui_submission(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(520, 110)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 490, 70))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Submission"))
        self.label.setText(_translate("Dialog", "Are you sure to submit and email the answers?"))
        #self.label_1.setText(_translate("Dialog", "Please enter the email address to send your answers to:"))
        #self.label_2.setText(_translate("Dialog", "Please input your name below:"))
        self.pushButton.setText(_translate("Dialog", "Yes"))
        self.pushButton_2.setText(_translate("Dialog", "No"))
