# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'query_widget.ui'
# Updated for PyQt6 compatibility

from PyQt6 import QtCore, QtWidgets

class Ui_QueryWindow(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(214, 618)
        Form.setAutoFillBackground(True)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 211, 611))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.horizontalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.createQueryPanel()
        QtCore.QMetaObject.connectSlotsByName(Form)

    def createQueryPanel(self):
        self.queryTypeGroupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.queryTypeGroupBox.setObjectName("queryTypeGroupBox")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.queryTypeGroupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 201, 191))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.queryTypeLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.queryTypeLayout.setContentsMargins(0, 0, 0, 0)
        self.queryTypeLayout.setObjectName("queryTypeLayout")
        self.queryListWidget = QtWidgets.QListWidget(self.verticalLayoutWidget_2)
        self.queryListWidget.setObjectName("queryListWidget")
        self.queryTypeLayout.addWidget(self.queryListWidget)
        self.verticalLayout.addWidget(self.queryTypeGroupBox)
        self.createQueryInputInterface()
        self.runQueryGroupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.runQueryGroupBox.setObjectName("runQueryGroupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.runQueryGroupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 20, 201, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.runQueryLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.runQueryLayout.setContentsMargins(0, 0, 0, 0)
        self.runQueryLayout.setObjectName("runQueryLayout")
        self.runQueryButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.runQueryButton.setText('Run Query')
        self.runQueryButton.setObjectName("runQueryButton")
        self.runQueryLayout.addWidget(self.runQueryButton)
        self.clearButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.clearButton.setText('Clear Output')
        self.clearButton.setObjectName("clearButton")
        self.runQueryLayout.addWidget(self.clearButton)
        self.verticalLayout.addWidget(self.runQueryGroupBox)
        
    def createQueryInputInterface(self):
        self.queryInputGroupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.queryInputGroupBox.setObjectName("queryInputGroupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.queryInputGroupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 20, 300, 191))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.queryInputLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.queryInputLayout.setContentsMargins(0, 0, 0, 0)
        self.queryInputLayout.setObjectName("queryInputLayout")
        self.file1Label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.file1Label.setObjectName("file1Label")
        self.queryInputLayout.addWidget(self.file1Label, 1, 0, 1, 1)
        self.file1ComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.file1ComboBox.setObjectName("file1ComboBox")
        self.queryInputLayout.addWidget(self.file1ComboBox, 1, 1, 1, 1)
        self.lineEditLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lineEditLabel.setObjectName("lineEditLabel")
        self.queryInputLayout.addWidget(self.lineEditLabel, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.queryInputLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.file2Label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.file2Label.setObjectName("file2Label")
        self.queryInputLayout.addWidget(self.file2Label, 2, 0, 1, 1)
        self.file2ComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.file2ComboBox.setObjectName("file2ComboBox")
        self.queryInputLayout.addWidget(self.file2ComboBox, 2, 1, 1, 1)
        self.file3Label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.file3Label.setObjectName("file3Label")
        self.queryInputLayout.addWidget(self.file3Label, 3, 0, 1, 1)
        self.file3ComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.file3ComboBox.setObjectName("file3ComboBox")
        self.queryInputLayout.addWidget(self.file3ComboBox, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.queryInputGroupBox)
